autoStartDemo: false
idleMinutes: 10

vpn:
  connectionNames:
    - KLEVER VPN
    - KLEVER VPN2
  checkIntervalSeconds: 5

rdp:
  host: 192.168.174.132
  port: 3389
  userName: KLO06001@dpc.msmash.ru
  checkIntervalSeconds: 5
  connectTimeoutSeconds: 2

automation:
  mouse:
    movementDurationMilliseconds: 300
    stepDelayMilliseconds: 10
